name: Test GitHub Actions

on:
  push:
    branches: [ database-demo ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Simple test
      run: |
        echo "🎉 GitHub Actions is working!"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Repository: ${{ github.repository }}"